In [1]:
import pandas as pd 
import plotly.graph_objects as go 
import numpy as np

In [6]:
pd.set_option("display.max_columns",None)

In [7]:
url = r"C:\works\learnings\statistics\bank-additional\bank-additional\bank-additional-full.csv"
df = pd.read_csv(url, sep=";", header= 0)
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [9]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB
None

In [11]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [12]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
stats_df = df[numeric_cols].describe().T
stats_df['variance'] = df[numeric_cols].var()
stats_df["skweness"] = df[numeric_cols].skew()
stats_df["kurtosis"] = df[numeric_cols].kurt()
stats_df.head()

,count,mean,std,min,25%,50%,75%,max,variance,skweness,kurtosis
age,41188.0,40.024060,10.421250,17.0,32.0,38.0,47.0,98.0,108.602451,0.784697,0.791312
duration,41188.0,258.285010,259.279249,0.0,102.0,180.0,319.0,4918.0,67225.728877,3.263141,20.247938
campaign,41188.0,2.567593,2.770014,1.0,1.0,2.0,3.0,56.0,7.672975,4.762507,36.979795
pdays,41188.0,962.475454,186.910907,0.0,999.0,999.0,999.0,999.0,34935.687284,-4.922190,22.229463
previous,41188.0,0.172963,0.494901,0.0,0.0,0.0,0.0,7.0,0.244927,3.832042,20.108816

**Correlation Matrix**

In [17]:
corr_matrix = df[numeric_cols].corr()

fig = go.Figure(
    data=[
        go.Heatmap(
            z = corr_matrix.values,
            x = corr_matrix.columns,
            y = corr_matrix.columns,
            colorscale="RdBu",
            zmid=0,
            text=corr_matrix.values,
            texttemplate='%{text:.2f}',
            textfont={"size": 10},
            colorbar=dict(title="Correlation")
        )
    ]
)

fig.update_layout(
    title='Correlation Heatmap',
    width=800,
    height=800,
    xaxis_title='Features',
    yaxis_title='Features',
    yaxis={'autorange': 'reversed'}
)

fig.show()

In [18]:
import plotly.figure_factory as ff 

for col in numeric_cols :
    fig = ff.create_distplot([df[col].dropna()], [col], show_hist= True , show_rug=False)
    fig.show()