In [1]:
import pandas as pd

In [5]:
df = pd.read_excel(r"C:\works\learnings\analysis\analysis.xlsx")
df.head()

  customer_id,order_date,product_category,quantity,price,discount,region
0      101,2024-01-15,Electronics,2,299.99,0.1,North
1         102,2024-01-16,Clothing,1,49.99,0.15,South
2     101,2024-01-20,Electronics,1,599.99,0.05,North
3               103,2024-01-22,Home,3,89.99,0.2,East
4             104,2024-01-25,Clothing,2,79.99,0,West

In [11]:
df.to_csv(r"C:\works\learnings\analysis\analysis.csv",index=False)

In [16]:
# Remove quotes and re-save cleanly
with open(r"C:\works\learnings\analysis\analysis.csv", "r") as f:
    data = f.read().replace('"', '')

with open(r"C:\works\learnings\analysis\analysis_clean.csv", "w") as f:
    f.write(data)

# Now read the clean version
df = pd.read_csv(r"C:\works\learnings\analysis\analysis_clean.csv")
df.head()

   customer_id  order_date product_category  quantity   price  discount region
0          101  2024-01-15      Electronics         2  299.99      0.10  North
1          102  2024-01-16         Clothing         1   49.99      0.15  South
2          101  2024-01-20      Electronics         1  599.99      0.05  North
3          103  2024-01-22             Home         3   89.99      0.20   East
4          104  2024-01-25         Clothing         2   79.99      0.00   West

In [17]:
df.describe()

       customer_id   quantity       price   discount
count     15.00000  15.000000   15.000000  15.000000
mean     103.60000   1.733333  257.323333   0.113333
std        2.22967   0.961150  224.514291   0.071880
min      101.00000   1.000000   29.990000   0.000000
25%      102.00000   1.000000   84.990000   0.075000
50%      103.00000   1.000000  199.990000   0.100000
75%      105.00000   2.000000  349.990000   0.150000
max      108.00000   4.000000  799.990000   0.250000

In [18]:
df.isna().sum()

customer_id         0
order_date          0
product_category    0
quantity            0
price               0
discount            0
region              0
dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       15 non-null     int64
 1   order_date        15 non-null     object
 2   product_category  15 non-null     object
 3   quantity          15 non-null     int64
 4   price             15 non-null     float64
 5   discount          15 non-null     float64
 6   region            15 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 972.0+ bytes

In [20]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [21]:
df["total_revnue"] = df["quantity"] * df["price"] * (1 - df["discount"])
df.head(3)

,customer_id,order_date,product_category,quantity,price,discount,region,total_revnue
0,101,2024-01-15,Electronics,2,299.99,0.10,North,539.9820
1,102,2024-01-16,Clothing,1,49.99,0.15,South,42.4915
2,101,2024-01-20,Electronics,1,599.99,0.05,North,569.9905

In [28]:
avg_order_by_region = df.groupby("region")["total_revnue"].mean()
print(avg_order_by_region)

region
East     201.978667
North    348.284400
South    308.114125
West     336.653833
Name: total_revnue, dtype: float64

In [29]:
df["avg_order_by_region"] = df["region"].map(avg_order_by_region)
df.head()

,customer_id,order_date,product_category,quantity,price,discount,region,total_revnue,avg_order_by_region
0,101,2024-01-15,Electronics,2,299.99,0.10,North,539.9820,348.284400
1,102,2024-01-16,Clothing,1,49.99,0.15,South,42.4915,308.114125
2,101,2024-01-20,Electronics,1,599.99,0.05,North,569.9905,348.284400
3,103,2024-01-22,Home,3,89.99,0.20,East,215.9760,201.978667
4,104,2024-01-25,Clothing,2,79.99,0.00,West,159.9800,336.653833

In [32]:
east_buying_product = df[df["region"] == "East"]["product_category"]
print(east_buying_product)

3         Home
7     Clothing
12        Home
Name: product_category, dtype: object

In [36]:
product_mix = df.groupby(["region", "product_category"]).size().reset_index(name = "order_count")
print(product_mix)

  region product_category  order_count
0   East         Clothing            1
1   East             Home            2
2  North         Clothing            1
3  North      Electronics            2
4  North             Home            2
5  South         Clothing            1
6  South      Electronics            3
7   West         Clothing            2
8   West      Electronics            1

In [35]:
product_avg = df.groupby("product_category")["total_revnue"].mean().reset_index()
product_avg

  product_category  total_revnue
0         Clothing    105.281700
1      Electronics    509.988000
2             Home    250.859875

In [41]:
product_discount = df.groupby(["region","discount", "product_category"]).size().reset_index()
print(product_discount)

   region  discount product_category  0
0    East      0.00             Home  1
1    East      0.20             Home  1
2    East      0.25         Clothing  1
3   North      0.05      Electronics  1
4   North      0.10      Electronics  1
5   North      0.10             Home  1
6   North      0.15             Home  1
7   North      0.20         Clothing  1
8   South      0.10      Electronics  2
9   South      0.15         Clothing  1
10  South      0.15      Electronics  1
11   West      0.00         Clothing  1
12   West      0.05      Electronics  1
13   West      0.10         Clothing  1

In [42]:
avg_discount = df.groupby("product_category")["discount"].mean().reset_index()
print(avg_discount)

  product_category  discount
0         Clothing  0.140000
1      Electronics  0.091667
2             Home  0.112500

In [44]:
most_sold_product = df.groupby(["region","product_category"])["order_date"].size().reset_index()
print(most_sold_product)

  region product_category  order_date
0   East         Clothing           1
1   East             Home           2
2  North         Clothing           1
3  North      Electronics           2
4  North             Home           2
5  South         Clothing           1
6  South      Electronics           3
7   West         Clothing           2
8   West      Electronics           1