In [1]:
import pandas as pd 
import numpy as np

In [2]:
order_item = pd.read_csv(r"C:\works\learnings\story_telling_insight_analysis\Data_folder\olist_order_items_dataset.csv")
order_review = pd.read_csv(r"C:\works\learnings\story_telling_insight_analysis\Data_folder\olist_order_reviews_dataset.csv")
order_dataset = pd.read_csv(r"C:\works\learnings\story_telling_insight_analysis\Data_folder\olist_orders_dataset.csv")
product_details = pd.read_csv(r"C:\works\learnings\story_telling_insight_analysis\Data_folder\olist_products_dataset.csv")
seller_details  = pd.read_csv(r"C:\works\learnings\story_telling_insight_analysis\Data_folder\olist_sellers_dataset.csv")

In [3]:
order_dataset.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
order_item.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [5]:
order_review.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [6]:
product_details.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [7]:
seller_details.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [8]:
order_dataset["order_delivered_customer_date"] = pd.to_datetime(order_dataset["order_delivered_customer_date"])
order_dataset["order_estimated_delivery_date"] = pd.to_datetime(order_dataset["order_estimated_delivery_date"])

In [9]:
order_dataset["Delay"] = order_dataset["order_delivered_customer_date"] - order_dataset["order_estimated_delivery_date"]
order_dataset.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Delay
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8 days +21:25:13
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6 days +15:27:45
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18 days +18:06:29
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13 days +00:28:42
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10 days +18:17:02

In [10]:
order_dataset["Delay"] = order_dataset["Delay"].dt.total_seconds() / 86400
delayed_order_dataset = order_dataset[order_dataset["Delay"] > 1]
delayed_order_dataset.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Delay
20,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,11.933171
25,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12,9.919375
41,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21,7.791238
57,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:15,2018-03-09 15:40:39,2018-03-15 00:31:19,2018-04-03 13:28:46,2018-04-02,1.561644
58,a685d016c8a26f71a0bb67821070e398,911e4c37f5cafe1604fe6767034bf1ae,delivered,2017-03-13 18:14:36,2017-03-13 18:14:36,2017-03-22 14:03:09,2017-04-06 13:37:16,2017-03-30,7.567546

In [13]:
delayed_order_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6535 entries, 20 to 99432
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       6535 non-null   object
 1   customer_id                    6535 non-null   object
 2   order_status                   6535 non-null   object
 3   order_purchase_timestamp       6535 non-null   object
 4   order_approved_at              6535 non-null   object
 5   order_delivered_carrier_date   6534 non-null   object
 6   order_delivered_customer_date  6535 non-null   datetime64[ns]
 7   order_estimated_delivery_date  6535 non-null   datetime64[ns]
 8   Delay                          6535 non-null   float64
dtypes: datetime64[ns](2), float64(1), object(6)
memory usage: 510.5+ KB

In [14]:
order_item.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [19]:
order = delayed_order_dataset.merge(order_item,on="order_id", how="left")
order["Delay"] = np.ceil(order["Delay"]) 
order.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Delay,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,203096f03d82e0dffbc41ebc2e2bcfb7,d2b091571da224a1b36412c18bc3bbfe,delivered,2017-09-18 14:31:30,2017-09-19 04:04:09,2017-10-06 17:50:03,2017-10-09 22:23:46,2017-09-28,12.0,1,5ac9d9e379c606e36a8094a6046f75dc,633ecdf879b94b5337cca303328e4a25,2017-09-25 04:04:09,109.90,8.96
1,fbf9ac61453ac646ce8ad9783d7d0af6,3a874b4d4c4b6543206ff5d89287f0c3,delivered,2018-02-20 23:46:53,2018-02-22 02:30:46,2018-02-26 22:25:22,2018-03-21 22:03:54,2018-03-12,10.0,1,7b717060aa783eb7f23a747a3a733dd7,c0563dd588b775f2e37747ef6ad6c92c,2018-02-28 02:30:44,109.90,15.53
2,6ea2f835b4556291ffdc53fa0b3b95e8,c7340080e394356141681bd4c9b8fe31,delivered,2017-11-24 21:27:48,2017-11-25 00:21:09,2017-12-13 21:14:05,2017-12-28 18:59:23,2017-12-21,8.0,1,be021417a6acb56b9b50d3fd2714baa8,f5f46307a4d15880ca14fab4ad9dfc9b,2017-11-30 00:21:09,339.00,17.12
3,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:15,2018-03-09 15:40:39,2018-03-15 00:31:19,2018-04-03 13:28:46,2018-04-02,2.0,1,b37b72d5a56f887725c2862184b8cab8,db4350fd57ae30082dec7acbaacc17f9,2018-03-15 15:30:45,22.99,22.85
4,66e4624ae69e7dc89bd50222b59f581f,684fa6da5134b9e4dab731e00011712d,delivered,2018-03-09 14:50:15,2018-03-09 15:40:39,2018-03-15 00:31:19,2018-04-03 13:28:46,2018-04-02,2.0,2,b37b72d5a56f887725c2862184b8cab8,db4350fd57ae30082dec7acbaacc17f9,2018-03-15 15:30:45,22.99,22.85

In [18]:
order.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7265 entries, 0 to 7264
Data columns (total 16 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       7265 non-null   object
 1   customer_id                    7265 non-null   object
 2   order_status                   7265 non-null   object
 3   order_purchase_timestamp       7265 non-null   object
 4   order_approved_at              7265 non-null   object
 5   order_delivered_carrier_date   7264 non-null   object
 6   order_delivered_customer_date  7265 non-null   datetime64[ns]
 7   order_estimated_delivery_date  7265 non-null   datetime64[ns]
 8   Delay                          7265 non-null   float64
 9   order_item_id                  7265 non-null   int64
 10  product_id                     7265 non-null   object
 11  seller_id                      7265 non-null   object
 12  shipping_limit_date            7265 non-null   object
 13  price                          7265 non-null   float64
 14  freight_value                  7265 non-null   float64
 15  Delay_days                     7265 non-null   float64
dtypes: datetime64[ns](2), float64(4), int64(1), object(9)
memory usage: 908.3+ KB

In [23]:
len(order[order["Delay"] > 3]["seller_id"])

5724

In [24]:
seller_delay = order.groupby("seller_id")["Delay"].agg(["count","mean","max"])
seller_delay = seller_delay.sort_values("count", ascending=False)
seller_delay.head(20)

                                  count       mean    max
seller_id
4a3ca9315b744ce9f8e9374361493884    189  12.047619  138.0
1f50f920176fa81dab994f9023523100    150  11.466667  144.0
4869f7a5dfa277a7dca6462dcf3b52b2    121  10.239669   31.0
7c67e1448b00f6e969d365cea6b010ab    120  11.900000  154.0
6560211a19b47992c3666cc44a7e94c0    102   8.549020   66.0
ea8482cd71df3c1969d7b9473ff13abc    100   9.100000  110.0
da8622b14eb17ae2831f4ac5b9dab84a     99  11.848485   97.0
955fee9216a65b617aa5c0531780ce60     95   8.915789   53.0
1025f0e2d44d7041d6cf58b6550e0bfa     95   8.063158   75.0
cc419e0650a3c5ba77189a1882b7556a     88   8.852273   37.0
8b321bb669392f5163d04c59e235e066     87  10.356322   67.0
06a2c3af7b3aee5d69171b0e14f0ee87     78   8.679487   28.0
620c87c171fb2a6dd6e8bb4dec959fc6     65  11.676923   78.0
8160255418d5aaa7dbdc9f4c64ebda44     64  13.359375  127.0
7d13fca15225358621be4086e1eb0964     64  12.406250   51.0
3d871de0142ce09b7081e2b9d1733cb1     62  10.725806   74.0
7a67c85e85bb2ce8582c35f2203ad736     60  13.700000  189.0
fa1c13f2614d7b5c4749cbc52fecda94     53  11.886792   61.0
1835b56ce799e6a4dc4eddc053f04066     49  10.061224   64.0
88460e8ebdecbfecb5f9601833981930     49  10.795918   33.0

In [25]:
order.groupby(pd.cut(order["Delay"], bins=[0,3,7,15,999]))["freight_value"].mean()

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_13412\681504762.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  order.groupby(pd.cut(order["Delay"], bins=[0,3,7,15,999]))["freight_value"].mean()

Delay
(0, 3]       20.755724
(3, 7]       22.023490
(7, 15]      23.690801
(15, 999]    24.190242
Name: freight_value, dtype: float64