In [1]:
import pandas as pd 
import numpy as np 
import plotly.graph_objects as go

In [9]:
pd.set_option("display.max_columns",None)

In [38]:
df = pd.read_csv(r"C:\works\learnings\logisitic_supply_chain\archive\DataCoSupplyChainDataset.csv", sep = ",", encoding="latin1")
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Id,Customer Lname,Customer Password,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,20755,Holloway,XXXXXXXXX,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,1360,13.110000,0.04,180517,327.75,0.29,1,327.75,314.640015,91.250000,Southeast Asia,Java Occidental,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,19492,Luna,XXXXXXXXX,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,1360,16.389999,0.05,179254,327.75,-0.80,1,327.75,311.359985,-249.089996,South Asia,Rajastán,PENDING,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,19491,Maldonado,XXXXXXXXX,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,1360,18.030001,0.06,179253,327.75,-0.80,1,327.75,309.720001,-247.779999,South Asia,Rajastán,CLOSED,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,19490,Tate,XXXXXXXXX,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,1360,22.940001,0.07,179252,327.75,0.08,1,327.75,304.809998,22.860001,Oceania,Queensland,COMPLETE,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,19489,Hendricks,XXXXXXXXX,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,1360,29.500000,0.09,179251,327.75,0.45,1,327.75,298.250000,134.210007,Oceania,Queensland,PENDING_PAYMENT,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [12]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,Longitude,Order Customer Id,Order Id,Order Item Cardprod Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,-84.915675,6691.379495,36221.894903,692.509764,20.664741,0.101668,90260.000000,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,21.433241,4162.918106,21045.379569,336.446807,21.800901,0.070415,52111.490959,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,-158.025986,1.000000,1.000000,19.000000,0.000000,0.000000,1.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,-98.446312,3258.500000,18057.000000,403.000000,5.400000,0.040000,45130.500000,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,-76.847908,6457.000000,36140.000000,627.000000,14.000000,0.100000,90260.000000,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,-66.370583,9779.000000,54144.000000,1004.000000,29.990000,0.160000,135389.500000,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,115.263077,20757.000000,77204.000000,1363.000000,500.000000,0.250000,180519.000000,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [13]:
df.isna().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [16]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Type,180519,4,DEBIT,69295,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Days for shipping (real),180519.0,NaN,NaN,NaN,3.497654,1.623722,0.0,2.0,3.0,5.0,6.0
Days for shipment (scheduled),180519.0,NaN,NaN,NaN,2.931847,1.374449,0.0,2.0,4.0,4.0,4.0
Benefit per order,180519.0,NaN,NaN,NaN,21.974989,104.433526,-4274.97998,7.0,31.52,64.800003,911.799988
Sales per customer,180519.0,NaN,NaN,NaN,183.107609,120.04367,7.49,104.379997,163.990005,247.399994,1939.98999
Delivery Status,180519,4,Late delivery,98977,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Late_delivery_risk,180519.0,NaN,NaN,NaN,0.548291,0.497664,0.0,0.0,1.0,1.0,1.0
Category Id,180519.0,NaN,NaN,NaN,31.851451,15.640064,2.0,18.0,29.0,45.0,76.0
Category Name,180519,50,Cleats,24551,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer City,180519,563,Caguas,66770,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Country,180519,2,EE. UU.,111146,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Email,180519,1,XXXXXXXXX,180519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Fname,180519,782,Mary,65150,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Id,180519.0,NaN,NaN,NaN,6691.379495,4162.918106,1.0,3258.5,6457.0,9779.0,20757.0
Customer Lname,180511,1109,Smith,64104,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Password,180519,1,XXXXXXXXX,180519,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Segment,180519,3,Consumer,93504,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer State,180519,46,PR,69373,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Street,180519,7458,9126 Wishing Expressway,122,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer Zipcode,180516.0,NaN,NaN,NaN,35921.126914,37542.461122,603.0,725.0,19380.0,78207.0,99205.0
Department Id,180519.0,NaN,NaN,NaN,5.44346,1.629246,2.0,4.0,5.0,7.0,12.0
Department Name,180519,11,Fan Shop,66861,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Latitude,180519.0,NaN,NaN,NaN,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,NaN,NaN,NaN,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Market,180519,5,LATAM,51594,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order City,180519,3597,Santo Domingo,2211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Country,180519,164,Estados Unidos,24840,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Customer Id,180519.0,NaN,NaN,NaN,6691.379495,4162.918106,1.0,3258.5,6457.0,9779.0,20757.0
order date (DateOrders),180519,65752,12/14/2016 12:29,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Id,180519.0,NaN,NaN,NaN,36221.894903,21045.379569,1.0,18057.0,36140.0,54144.0,77204.0
Order Item Cardprod Id,180519.0,NaN,NaN,NaN,692.509764,336.446807,19.0,403.0,627.0,1004.0,1363.0
Order Item Discount,180519.0,NaN,NaN,NaN,20.664741,21.800901,0.0,5.4,14.0,29.99,500.0
Order Item Discount Rate,180519.0,NaN,NaN,NaN,0.101668,0.070415,0.0,0.04,0.1,0.16,0.25
Order Item Id,180519.0,NaN,NaN,NaN,90260.0,52111.490959,1.0,45130.5,90260.0,135389.5,180519.0
Order Item Product Price,180519.0,NaN,NaN,NaN,141.23255,139.732492,9.99,50.0,59.990002,199.990005,1999.98999
Order Item Profit Ratio,180519.0,NaN,NaN,NaN,0.120647,0.466796,-2.75,0.08,0.27,0.36,0.5
Order Item Quantity,180519.0,NaN,NaN,NaN,2.127638,1.453451,1.0,1.0,1.0,3.0,5.0
Sales,180519.0,NaN,NaN,NaN,203.772096,132.273077,9.99,119.980003,199.919998,299.950012,1999.98999
Order Item Total,180519.0,NaN,NaN,NaN,183.107609,120.04367,7.49,104.379997,163.990005,247.399994,1939.98999
Order Profit Per Order,180519.0,NaN,NaN,NaN,21.974989,104.433526,-4274.97998,7.0,31.52,64.800003,911.799988
Order Region,180519,23,Central America,28341,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order State,180519,1089,Inglaterra,6722,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Status,180519,9,COMPLETE,59491,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order Zipcode,24840.0,NaN,NaN,NaN,55426.132327,31919.279101,1040.0,23464.0,59405.0,90008.0,99301.0
Product Card Id,180519.0,NaN,NaN,NaN,692.509764,336.446807,19.0,403.0,627.0,1004.0,1363.0
Product Category Id,180519.0,NaN,NaN,NaN,31.851451,15.640064,2.0,18.0,29.0,45.0,76.0
Product Description,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Image,180519,118,http://images.acmesports.sports/Perfect+Fitnes...,24515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Name,180519,118,Perfect Fitness Perfect Rip Deck,24515,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product Price,180519.0,NaN,NaN,NaN,141.23255,139.732492,9.99,50.0,59.990002,199.990005,1999.98999
Product Status,180519.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shipping date (DateOrders),180519,63701,1/5/2016 5:58,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shipping Mode,180519,4,Standard Class,107752,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
columns = df.columns
id_named_columns = []
for  col in columns:
    if "Id" in col :
        id_named_columns.append(col)
id_named_columns

['Category Id',
 'Customer Id',
 'Department Id',
 'Order Customer Id',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Id',
 'Product Card Id',
 'Product Category Id']

In [23]:
id_named_columns_df = df[id_named_columns]
id_named_columns_df.head()

,Category Id,Customer Id,Department Id,Order Customer Id,Order Id,Order Item Cardprod Id,Order Item Id,Product Card Id,Product Category Id
0,73,20755,2,20755,77202,1360,180517,1360,73
1,73,19492,2,19492,75939,1360,179254,1360,73
2,73,19491,2,19491,75938,1360,179253,1360,73
3,73,19490,2,19490,75937,1360,179252,1360,73
4,73,19489,2,19489,75936,1360,179251,1360,73

In [29]:
sum((id_named_columns_df["Customer Id"].values) != (id_named_columns_df["Order Customer Id"].values))

0

In [32]:
pairs = [
    ("Category Id", "Product Category Id"),
    ("Product Card Id", "Order Item Cardprod Id"),
    ("Benefit per order", "Order Profit Per Order"),
    ("Sales per customer", "Order Item Total"),
    ("Product Price", "Order Item Product Price"),
]
drop = []
for c1, c2 in pairs:
    print(f"{c1} == {c2} :", (df[c1] == df[c2]).all())
    drop.append(c2)

Category Id == Product Category Id : True
Product Card Id == Order Item Cardprod Id : True
Benefit per order == Order Profit Per Order : True
Sales per customer == Order Item Total : True
Product Price == Order Item Product Price : True

In [31]:
df["Order Id"].nunique(), len(df)

(65752, 180519)

In [41]:
df = df.drop(columns=["Product Status"])
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,Customer Country,Customer Fname,Customer Id,Customer Lname,Customer Segment,Customer State,Customer Street,Customer Zipcode,Department Id,Department Name,Latitude,Longitude,Market,Order City,Order Country,Order Customer Id,order date (DateOrders),Order Id,Order Item Discount,Order Item Discount Rate,Order Item Id,Order Item Profit Ratio,Order Item Quantity,Sales,Order Region,Order State,Order Status,Product Card Id,Product Name,Product Price,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Cally,20755,Holloway,Consumer,PR,5365 Noble Nectar Island,725.0,2,Fitness,18.251453,-66.037056,Pacific Asia,Bekasi,Indonesia,20755,1/31/2018 22:56,77202,13.110000,0.04,180517,0.29,1,327.75,Southeast Asia,Java Occidental,COMPLETE,1360,Smart watch,327.75,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,Puerto Rico,Irene,19492,Luna,Consumer,PR,2679 Rustic Loop,725.0,2,Fitness,18.279451,-66.037064,Pacific Asia,Bikaner,India,19492,1/13/2018 12:27,75939,16.389999,0.05,179254,-0.80,1,327.75,South Asia,Rajastán,PENDING,1360,Smart watch,327.75,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,EE. UU.,Gillian,19491,Maldonado,Consumer,CA,8510 Round Bear Gate,95125.0,2,Fitness,37.292233,-121.881279,Pacific Asia,Bikaner,India,19491,1/13/2018 12:06,75938,18.030001,0.06,179253,-0.80,1,327.75,South Asia,Rajastán,CLOSED,1360,Smart watch,327.75,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,EE. UU.,Tana,19490,Tate,Home Office,CA,3200 Amber Bend,90027.0,2,Fitness,34.125946,-118.291016,Pacific Asia,Townsville,Australia,19490,1/13/2018 11:45,75937,22.940001,0.07,179252,0.08,1,327.75,Oceania,Queensland,COMPLETE,1360,Smart watch,327.75,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,Puerto Rico,Orli,19489,Hendricks,Corporate,PR,8671 Iron Anchor Corners,725.0,2,Fitness,18.253769,-66.037048,Pacific Asia,Townsville,Australia,19489,1/13/2018 11:24,75936,29.500000,0.09,179251,0.45,1,327.75,Oceania,Queensland,PENDING_PAYMENT,1360,Smart watch,327.75,1/15/2018 11:24,Standard Class

In [44]:
df.groupby("Order Id")["Order Item Id"].count().reset_index()

       Order Id  Order Item Id
0             1              1
1             2              3
2             4              4
3             5              5
4             7              3
...         ...            ...
65747     77200              1
65748     77201              1
65749     77202              1
65750     77203              1
65751     77204              1

[65752 rows x 2 columns]