In [1]:
import pandas as pd 
import numpy as np 
import plotly.graph_objects as go

In [2]:
df = pd.read_excel(r"C:\works\learnings\Advance_EDA\online_retail_II.xlsx")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# Data Integrity Audit Analysis

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[ns]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 32.1+ MB

In [4]:
null_mask = df["Customer ID"].isna()
print(df[null_mask]["Price"].mean())
print(df[null_mask]["Price"].sum())

7.788749895762878
840616.4100000001

In [5]:
total = df[df["Customer ID"].isna()]["Price"].sum()

In [6]:
total_sum = df["Price"].sum()

In [7]:
print(f"Missing customer Id revenue :  {round((total  / total_sum)* 100,3)}%")

Missing customer Id revenue :  34.119%

In [8]:
anonymous_revenue_based_on_country = df[null_mask].groupby("Country")["Price"].sum().reset_index()
anonymous_revenue_based_on_country["revenue_percentage"] =  (anonymous_revenue_based_on_country["Price"]/total_sum)* 100
anonymous_revenue_based_on_country.sort_values(by = "revenue_percentage", ascending=False)

                 Country      Price  revenue_percentage
11        United Kingdom  821327.20           33.335795
4              Hong Kong    8715.38            0.353737
2                   EIRE    5432.08            0.220476
8                    RSA    2956.29            0.119989
10  United Arab Emirates    1153.94            0.046836
0                Bahrain     261.36            0.010608
7               Portugal     239.38            0.009716
3                 France     127.22            0.005164
5                Lebanon     116.17            0.004715
9                 Sweden     113.45            0.004605
1                Bermuda      84.70            0.003438
12           Unspecified      82.44            0.003346
6                Nigeria       6.80            0.000276

In [9]:
df[null_mask & (df["Country"] == "United Kingdom")]["Invoice"].str[0].value_counts()

Invoice
C    322
A      3
Name: count, dtype: int64

In [10]:
df["Invoice"].str[0].value_counts()

Invoice
C    10206
A        3
Name: count, dtype: int64

In [11]:
df[null_mask & (df["Country"] == "United Kingdom")].groupby(df["InvoiceDate"].dt.to_period("M")).size()

InvoiceDate
2009-12    13389
2010-01     9113
2010-02     5337
2010-03     8328
2010-04     6026
2010-05     5674
2010-06     7994
2010-07     5477
2010-08     6184
2010-09     6637
2010-10     8317
2010-11    16244
2010-12     7709
Freq: M, dtype: int64

In [12]:
sales_df = df[df["Customer ID"].notna()]
sales_df

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [13]:
sales_df["Customer ID"].isna().sum()

0

In [14]:
returns_df = sales_df[sales_df["Invoice"].str.startswith("C", na=False)]
sales_df = sales_df[~sales_df["Invoice"].str.startswith("C", na=False)]

In [15]:
print(sales_df.shape)
print(sales_df["Customer ID"].isna().sum())  # must be 0
print(returns_df.shape)

(407695, 8)
0
(9839, 8)

In [16]:
sales_df["Revenue"] = sales_df["Quantity"] * sales_df["Price"]

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17340\2845090627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales_df["Revenue"] = sales_df["Quantity"] * sales_df["Price"]

In [17]:
sales_df[sales_df["Revenue"] <= 0].count()

Invoice        31
StockCode      31
Description    31
Quantity       31
InvoiceDate    31
Price          31
Customer ID    31
Country        31
Revenue        31
dtype: int64

In [18]:
sales_df[sales_df["Revenue"] <= 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0,16126.0,United Kingdom,0.0
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0,15658.0,United Kingdom,0.0
16107,490727,M,Manual,1,2009-12-07 16:38:00,0.0,17231.0,United Kingdom,0.0
18738,490961,22065,CHRISTMAS PUDDING TRINKET POT,1,2009-12-08 15:25:00,0.0,14108.0,United Kingdom,0.0
18739,490961,22142,CHRISTMAS CRAFT WHITE FAIRY,12,2009-12-08 15:25:00,0.0,14108.0,United Kingdom,0.0
32916,492079,85042,ANTIQUE LILY FAIRY LIGHTS,8,2009-12-15 13:49:00,0.0,15070.0,United Kingdom,0.0
40101,492760,21143,ANTIQUE GLASS HEART DECORATION,12,2009-12-18 14:22:00,0.0,18071.0,United Kingdom,0.0
47126,493761,79320,FLAMINGO LIGHTS,24,2010-01-06 14:54:00,0.0,14258.0,United Kingdom,0.0
48342,493899,22355,"CHARLOTTE BAG , SUKI DESIGN",10,2010-01-08 10:43:00,0.0,12417.0,Belgium,0.0
57619,494607,21533,RETRO SPOT LARGE MILK JUG,12,2010-01-15 12:43:00,0.0,16858.0,United Kingdom,0.0
89084,497819,TEST001,This is a test product.,5,2010-02-12 14:58:00,0.0,14103.0,United Kingdom,0.0
89180,497843,TEST001,This is a test product.,5,2010-02-12 15:47:00,0.0,14827.0,United Kingdom,0.0
111348,500073,21662,VINTAGE GLASS COFFEE CADDY,1,2010-03-04 11:44:00,0.0,13047.0,United Kingdom,0.0
149201,503585,22459,CAST IRON HOOK GARDEN TROWEL,8,2010-04-01 17:13:00,0.0,13047.0,United Kingdom,0.0
149202,503585,22458,CAST IRON HOOK GARDEN FORK,8,2010-04-01 17:13:00,0.0,13047.0,United Kingdom,0.0
166143,505083,22376,AIRLINE BAG VINTAGE JET SET WHITE,1,2010-04-20 09:56:00,0.0,12623.0,Germany,0.0
232526,511902,21765,HANGING METAL BIRD BATH,1,2010-06-11 11:12:00,0.0,12748.0,United Kingdom,0.0
240455,512609,20914,SET/5 RED SPOTTY LID GLASS BOWLS,2,2010-06-17 10:12:00,0.0,14045.0,United Kingdom,0.0
248583,513416,22423,REGENCY CAKESTAND 3 TIER,5,2010-06-24 12:34:00,0.0,13089.0,United Kingdom,0.0
276858,516304,22690,DOORMAT HOME SWEET HOME BLUE,6,2010-07-19 13:13:00,0.0,14025.0,United Kingdom,0.0
296375,518231,22472,TV DINNER TRAY DOLLY GIRL,9,2010-08-05 15:28:00,0.0,12471.0,Germany,0.0
327801,521375,22202,MILK PAN PINK RETROSPOT,3,2010-09-05 11:58:00,0.0,12647.0,Germany,0.0
358820,524181,46000M,POLYESTER FILLER PAD 45x45cm,648,2010-09-27 16:59:00,0.0,17450.0,United Kingdom,0.0
364333,524701,22218,CAKE STAND LACE WHITE,2,2010-09-30 12:19:00,0.0,17667.0,United Kingdom,0.0
392008,527084,22630,DOLLY GIRL LUNCH BOX,64,2010-10-14 15:33:00,0.0,14646.0,Netherlands,0.0
400047,527696,22121,NOEL WOODEN BLOCK LETTERS,1,2010-10-18 15:13:00,0.0,13554.0,United Kingdom,0.0
439309,531361,21843,RED RETROSPOT CAKE STAND,2,2010-11-07 14:26:00,0.0,12820.0,United Kingdom,0.0
453705,532470,22624,IVORY KITCHEN SCALES,2,2010-11-12 11:41:00,0.0,12647.0,Germany,0.0
471775,533822,22846,BREAD BIN DINER STYLE RED,1,2010-11-19 09:40:00,0.0,12647.0,Germany,0.0
471776,533822,22845,VINTAGE CREAM CAT FOOD CONTAINER,1,2010-11-19 09:40:00,0.0,12647.0,Germany,0.0
512240,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany,0.0

In [19]:
sales_df = sales_df[sales_df["Revenue"] > 0]

In [20]:
most_generated_revenue = sales_df.groupby("Customer ID")["Revenue"].sum().reset_index()
most_generated_revenue.sort_values(by = "Revenue", ascending= False)[:20]

total_revenue = most_generated_revenue["Revenue"].sum()
most_generated_revenue_sorted = most_generated_revenue.sort_values("Revenue", ascending=False).copy()
most_generated_revenue_sorted["cumulative_revenue"] = most_generated_revenue_sorted["Revenue"].cumsum()
most_generated_revenue_sorted["cumulative_pct"] = most_generated_revenue_sorted["cumulative_revenue"] / total_revenue * 100
most_generated_revenue_sorted["customer_pct"] = np.arange(1, len(most_generated_revenue_sorted) + 1) / len(most_generated_revenue_sorted) * 100

In [21]:
most_generated_revenue_sorted.sort_values(by = "cumulative_revenue", ascending= False)

      Customer ID    Revenue  cumulative_revenue  cumulative_pct  customer_pct
1229      14095.0       2.95         8832003.274      100.000000    100.000000
1012      13788.0       3.75         8832000.324       99.999967     99.976809
2556      15913.0       6.30         8831996.574       99.999924     99.953618
1937      15040.0       7.49         8831990.274       99.999853     99.930427
4193      18115.0       9.70         8831982.784       99.999768     99.907236
...           ...        ...                 ...             ...           ...
939       13694.0  131443.19         1077718.350       12.202422      0.115955
1840      14911.0  152147.57          946275.160       10.714162      0.092764
1269      14156.0  196566.74          794127.590        8.991478      0.069573
1637      14646.0  248396.50          597560.850        6.765859      0.046382
4183      18102.0  349164.35          349164.350        3.953399      0.023191

[4312 rows x 5 columns]

In [22]:
threshold = most_generated_revenue_sorted[most_generated_revenue_sorted["cumulative_pct"] >= 80].iloc[0]
print(threshold)

Customer ID           1.662000e+04
Revenue               1.579970e+03
cumulative_revenue    7.067136e+06
cumulative_pct        8.001736e+01
customer_pct          2.727273e+01
Name: 3083, dtype: float64

In [23]:
country_revenue = sales_df.groupby("Country").agg(
    total_revenue = ("Revenue", "sum"),
    total_orders = ("Invoice","nunique")
).reset_index()
country_revenue["avg_basket"] = country_revenue["total_revenue"] / country_revenue["total_orders"]
country_revenue["revenue_pct"] = country_revenue["total_revenue"] / country_revenue["total_revenue"].sum() * 100
country_revenue.sort_values("avg_basket", ascending=False)

,Country,total_revenue,total_orders,avg_basket,revenue_pct
23,Norway,23944.180,11,2176.743636,0.271107
21,Netherlands,268786.000,135,1991.007407,3.043319
8,Denmark,50906.850,26,1957.955769,0.576391
15,Israel,3199.400,2,1599.700000,0.036225
31,Thailand,3070.540,2,1535.270000,0.034766
20,Malta,5373.500,4,1343.375000,0.060841
9,EIRE,356085.210,316,1126.851930,4.031760
13,Greece,14335.670,13,1102.743846,0.162315
30,Switzerland,43921.390,40,1098.034750,0.497298
27,Singapore,4037.770,4,1009.442500,0.045717
26,RSA,931.430,1,931.430000,0.010546
33,United Arab Emirates,7300.410,8,912.551250,0.082659
6,Channel Islands,24546.320,30,818.210667,0.277925
19,Lithuania,4892.680,6,815.446667,0.055397
0,Australia,31446.800,40,786.170000,0.356055
29,Sweden,53171.390,68,781.932206,0.602031
35,Unspecified,5946.580,8,743.322500,0.067330
28,Spain,47601.420,66,721.233636,0.538965
14,Iceland,1323.320,2,661.660000,0.014983
11,France,146215.420,236,619.556864,1.655518
5,Canada,1216.660,2,608.330000,0.013776
17,Japan,9722.020,16,607.626250,0.110077
25,Portugal,23845.410,40,596.135250,0.269989
12,Germany,202395.321,347,583.271818,2.291613
18,Korea,1118.510,2,559.255000,0.012664
7,Cyprus,11389.750,21,542.369048,0.128960
16,Italy,15067.180,28,538.113571,0.170598
36,West Indies,536.410,1,536.410000,0.006073
1,Austria,13414.330,28,479.083214,0.151883
3,Belgium,24557.080,52,472.251538,0.278047
10,Finland,7379.460,16,461.216250,0.083554
34,United Kingdom,7414755.963,17612,421.005903,83.953275
2,Bahrain,805.970,2,402.985000,0.009126
24,Poland,3567.800,10,356.780000,0.040396
32,USA,4786.470,15,319.098000,0.054195
4,Brazil,268.270,1,268.270000,0.003037
22,Nigeria,140.390,2,70.195000,0.001590

In [24]:
sales_df.groupby("Country")["Quantity"].mean().sort_values(ascending=False).head(10)

Country
Denmark        549.497608
Netherlands     67.283254
Sweden          60.402074
Japan           44.579268
Thailand        33.578947
Australia       32.046032
France          29.653016
Norway          21.553425
EIRE            21.326907
Switzerland     19.021368
Name: Quantity, dtype: float64

In [25]:
sales_df[sales_df["Country"] == "United Kingdom"]["Quantity"].mean()

11.99305797066285

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv(r"C:\works\learnings\Advance_EDA\superstore_orders.csv")
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country/Region,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,11/8/2020,11/11/2020,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,11/8/2020,11/11/2020,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,6/12/2020,6/16/2020,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,10/11/2019,10/18/2019,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,10/11/2019,10/18/2019,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [28]:
Eighty_pct_sales =( df["Sales"].sum()) * 0.8
Eighty_pct_sales

1837760.6882400003

In [29]:
product_group_sales = df.groupby("Product_ID")["Sales"].sum().reset_index().sort_values("Sales", ascending=False)
product_group_sales["cumulative_sum"] = product_group_sales["Sales"].cumsum()
product_group_sales[product_group_sales["cumulative_sum"] <= Eighty_pct_sales ][["Product_ID","Sales","cumulative_sum"]][:415]

           Product_ID      Sales  cumulative_sum
1614  TEC-CO-10004722  61599.824    6.159982e+04
776   OFF-BI-10003527  27453.384    8.905321e+04
1642  TEC-MA-10002412  22638.480    1.116917e+05
80    FUR-CH-10002024  21870.576    1.335623e+05
691   OFF-BI-10001359  19823.479    1.533857e+05
...               ...        ...             ...
1640  TEC-MA-10002178   1391.400    1.831706e+06
1840  TEC-PH-10004434   1386.690    1.833093e+06
1738  TEC-PH-10001750   1385.790    1.834479e+06
421   OFF-AP-10002311   1383.081    1.835862e+06
1670  TEC-MA-10004212   1379.920    1.837242e+06

[413 rows x 3 columns]

In [30]:
mask = product_group_sales["cumulative_sum"] <= Eighty_pct_sales
# include one extra row (the one that crosses the threshold)
cutoff_idx = mask.sum()  # number of True rows
product_group_sales.iloc[:cutoff_idx + 1][["Product_ID", "Sales", "cumulative_sum"]]

           Product_ID      Sales  cumulative_sum
1614  TEC-CO-10004722  61599.824    6.159982e+04
776   OFF-BI-10003527  27453.384    8.905321e+04
1642  TEC-MA-10002412  22638.480    1.116917e+05
80    FUR-CH-10002024  21870.576    1.335623e+05
691   OFF-BI-10001359  19823.479    1.533857e+05
...               ...        ...             ...
1840  TEC-PH-10004434   1386.690    1.833093e+06
1738  TEC-PH-10001750   1385.790    1.834479e+06
421   OFF-AP-10002311   1383.081    1.835862e+06
1670  TEC-MA-10004212   1379.920    1.837242e+06
35    FUR-BO-10003893   1368.262    1.838610e+06

[414 rows x 3 columns]

In [31]:
df.columns

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country/Region', 'City',
       'State', 'Postal_Code', 'Region', 'Product_ID', 'Category',
       'Sub_Category', 'Product_Name', 'Sales', 'Quantity', 'Discount',
       'Profit'],
      dtype='object')

In [32]:
df.dtypes

Row_ID              int64
Order_ID           object
Order_Date         object
Ship_Date          object
Ship_Mode          object
Customer_ID        object
Customer_Name      object
Segment            object
Country/Region     object
City               object
State              object
Postal_Code       float64
Region             object
Product_ID         object
Category           object
Sub_Category       object
Product_Name       object
Sales             float64
Quantity            int64
Discount          float64
Profit            float64
dtype: object

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_ID          9994 non-null   int64
 1   Order_ID        9994 non-null   object
 2   Order_Date      9994 non-null   object
 3   Ship_Date       9994 non-null   object
 4   Ship_Mode       9994 non-null   object
 5   Customer_ID     9994 non-null   object
 6   Customer_Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country/Region  9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal_Code     9983 non-null   float64
 12  Region          9994 non-null   object
 13  Product_ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub_Category    9994 non-null   object
 16  Product_Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [34]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = "Sagpenty1"  # put your exact password here
engine = create_engine(f"postgresql://postgres:{quote_plus(password)}@localhost:5432/postgres")

In [35]:
import pandas as pd 
df = pd.read_excel(r"C:\works\learnings\Advance_EDA\friend.xls")

In [36]:
df.columns = df.columns.str.lower()
df.to_sql("friend", engine, if_exists="replace", index=False)

8

In [37]:
friend = pd.read_excel(r"C:\works\learnings\Advance_EDA\friend.xls")
person = pd.read_excel(r"C:\works\learnings\Advance_EDA\person.xls")

In [38]:
friend

   PersonID  FriendID
0         1         2
1         1         3
2         2         1
3         2         3
4         3         5
5         4         2
6         4         3
7         4         5

In [39]:
person

   PersonID   Name                  Email  Score
0         1  Alice  alice2018@hotmail.com     88
1         2    Bob    bob2018@hotmail.com     11
2         3  Davis  davis2018@hotmail.com     27
3         4   Tara   tara2018@hotmail.com     45
4         5   John   john2018@hotmail.com     63

In [42]:
id_details

   PersonID_x  FriendID  PersonID_y   Name                  Email  Score
0           1         2           2    Bob    bob2018@hotmail.com     11
1           1         3           3  Davis  davis2018@hotmail.com     27
2           2         1           1  Alice  alice2018@hotmail.com     88
3           2         3           3  Davis  davis2018@hotmail.com     27
4           3         5           5   John   john2018@hotmail.com     63
5           4         2           2    Bob    bob2018@hotmail.com     11
6           4         3           3  Davis  davis2018@hotmail.com     27
7           4         5           5   John   john2018@hotmail.com     63

In [41]:
id_details = friend.merge(person, left_on= "FriendID", right_on= "PersonID", how="left")
id_details_sum = id_details.groupby("PersonID_x").agg({
    "Score" : ["sum"],
    "FriendID" : ["count"]
}).reset_index()
id_details_sum.columns = [ "_".join(col)  for col in id_details_sum.columns]
id_details_sum = id_details_sum[id_details_sum["Score_sum"] >= 100]

In [43]:
final_df = id_details_sum.merge(person, left_on="PersonID_x_", right_on="PersonID",how="left")
final_df.rename(columns={"PersonID_x_" : "ID","Score_sum" : "Total_Score"}, inplace=True)
final_df[["ID","Name","Total_Score","FriendID_count"]]

   ID  Name  Total_Score  FriendID_count
0   2   Bob          115               2
1   4  Tara          101               3

In [44]:
friend_names = id_details[id_details["PersonID_x"].isin(final_df["ID"])]
friend_names = friend_names.groupby("PersonID_x")["Name"].apply(list).reset_index()
result = final_df.merge(friend_names, left_on="ID", right_on= "PersonID_x", how= "inner")
result.rename(columns={"Name_y" : "Friends_name","Name_x" : "Name"},inplace= True)
result[["ID","Name","Total_Score","FriendID_count","Friends_name"]]

   ID  Name  Total_Score  FriendID_count        Friends_name
0   2   Bob          115               2      [Alice, Davis]
1   4  Tara          101               3  [Bob, Davis, John]